server:
  port: 8305
spring:
  application:
    name: community
eureka:
  client:
    service-url:
      ##eureka
      defaultZone: http://localhost:8021/eureka,http://localhost:8020/eureka
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh