spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liu4532617/community-config.git
          username: liulin4532617@163.com
          password: QazWsx2018
          basedir: F:\\liulinspace\\baseDir
          search-paths: /**
      label: master
  application:
    name: configserver
eureka:
  client:
    service-url:
      ##config 配置eureka 的集群地址
      defaultZone: http://localhost:8021/eureka,http://localhost:8020/eureka

